version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: browers-api:1.0
    container_name: browers-api
    ports:
      - "${PORT:-5050}:5050"
    environment:
      - PORT=${PORT:-5050}
      - JWT_SECRET=${JWT_SECRET}
      - DB_URL=${DB_URL}
    volumes:
      - ./api:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-5050}/health"]
      interval: 30s
      timeout: 10s
      retries: 3